@startuml
title: "RogueLike"

namespace RogueLike{

	namespace Managers{
		class DungeonManager{
		}
		class StagesManager{
		}
		class CharactersManager{
		}
		class TimeManager{
		}
	}

	namespace Stages{
		abstract StageGenerator{
			+ void GenerateStage()
		}
	}

	namespace Characters{
		class CharacterCore{

		}
		namespace Players{
			class PlayerCore{

			}
		}
	}
}

@enduml