@startuml
title: "sequence"

loop プレイヤーが脱出もしくは死亡するまで
	activate プレイヤー入力待ち
		loop ターン経過行動をするまで
			alt 入力[移動]
				プレイヤー入力待ち -> プレイヤー移動処理
				プレイヤー移動処理 -> アニメーション開始
			else 入力[攻撃]
				プレイヤー入力待ち -> プレイヤー攻撃処理
				プレイヤー攻撃処理 -> アニメーション開始
			else 入力[アイテム]
				プレイヤー入力待ち -> アイテム使用処理
				アイテム使用処理 -> アニメーション開始
			end
		end
	activate プレイヤーアニメーション開始
		プレイヤーアニメーション開始 -> プレイヤーアニメーション終了
	deactivate プレイヤーアニメーション開始
	deactivate プレイヤー入力待ち
	プレイヤー行動待ち -> 敵行動
	deactivate プレイヤー行動待ち
	activate 敵行動
		loop 敵全員分処理するまで
			敵行動 -> 敵の行動決定
			敵の行動決定 --> 敵行動
		end
	敵行動 -> プレイヤー行動
	deactivate 敵行動
	敵行動-> 味方行動
	activate 味方行動
	味方行動 -> 味方行動選択
	味方行動選択 --> 味方行動
	味方行動 --> プレイヤー行動
	deactivate 味方行動
end
@enduml